#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'

# Border
bspc config focused_border_color "#ffb86c"
bspc config normal_border_color "#44475a"
bspc config active_border_color "#f1fa8c"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -CGb &
# Network Applet
#nm-applet --indicator &
# Redshift
redshift &
# Cursor
xsetroot -cursor_name left_ptr &
